// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VarnAI.WeatherSense.Infrastructure.Persistence;

#nullable disable

namespace VarnAI.WeatherSense.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WeatherSenseDbContext))]
    [Migration("20260919151557_InitialWeatherSense")]
    partial class InitialWeatherSense
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VarnAI.WeatherSense.Domain.Entities.WeatherCollectionExecution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("LocationsFailed")
                        .HasColumnType("int");

                    b.Property<int>("LocationsProcessed")
                        .HasColumnType("int");

                    b.Property<int>("LocationsSucceeded")
                        .HasColumnType("int");

                    b.Property<int>("RecordsInserted")
                        .HasColumnType("int");

                    b.Property<int>("RecordsSkipped")
                        .HasColumnType("int");

                    b.Property<int>("RequestedForecastDays")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TriggerSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc")
                        .HasDatabaseName("IX_WeatherCollectionExecutions_StartedAtUtc");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_WeatherCollectionExecutions_Status");

                    b.ToTable("WeatherCollectionExecutions", (string)null);
                });

            modelBuilder.Entity("VarnAI.WeatherSense.Domain.Entities.WeatherForecast", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("CloudCoverPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("Et0Mm")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("FeelsLikeTemperatureC")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTimeOffset>("ForecastForLocal")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ForecastForUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ForecastGeneratedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("PrecipitationMm")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("PrecipitationProbabilityPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("PressureHpa")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderModel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("RainMm")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("RelativeHumidityPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("SoilMoisture0To7Cm")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal?>("SoilMoisture100To255Cm")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal?>("SoilMoisture28To100Cm")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal?>("SoilMoisture7To28Cm")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal?>("SoilTemperatureC")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("SolarRadiationWm2")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("TemperatureC")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("WeatherCode")
                        .HasColumnType("int");

                    b.Property<string>("WeatherDescription")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WeatherLocationId")
                        .HasColumnType("int");

                    b.Property<decimal?>("WindDirectionDegrees")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("WindGustKmh")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("WindSpeedKmh")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("WeatherLocationId", "ForecastForUtc")
                        .HasDatabaseName("IX_WeatherForecasts_Location_ForecastForUtc");

                    b.HasIndex("WeatherLocationId", "ForecastGeneratedAtUtc")
                        .HasDatabaseName("IX_WeatherForecasts_Location_ForecastGeneratedAtUtc");

                    b.HasIndex("WeatherLocationId", "Provider", "ForecastGeneratedAtUtc", "ForecastForUtc")
                        .IsUnique()
                        .HasDatabaseName("IX_WeatherForecasts_Snapshot_Unique");

                    b.ToTable("WeatherForecasts", (string)null);
                });

            modelBuilder.Entity("VarnAI.WeatherSense.Domain.Entities.WeatherLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("CollectionEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderLocationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_WeatherLocations_Code");

                    b.HasIndex("IsActive", "CollectionEnabled")
                        .HasDatabaseName("IX_WeatherLocations_IsActive_CollectionEnabled");

                    b.ToTable("WeatherLocations", (string)null);
                });

            modelBuilder.Entity("VarnAI.WeatherSense.Domain.Entities.WeatherLocationExecutionDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CollectionExecutionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("RecordsInserted")
                        .HasColumnType("int");

                    b.Property<int>("RecordsSkipped")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WeatherLocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeatherLocationId");

                    b.HasIndex("CollectionExecutionId", "WeatherLocationId")
                        .HasDatabaseName("IX_WeatherLocationExecutionDetails_Execution_Location");

                    b.ToTable("WeatherLocationExecutionDetails", (string)null);
                });

            modelBuilder.Entity("VarnAI.WeatherSense.Domain.Entities.WeatherObservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("CloudCoverPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Et0Mm")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("FeelsLikeTemperatureC")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTimeOffset>("ObservedAtLocal")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("PrecipitationMm")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("PrecipitationProbabilityPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("PressureHpa")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderRecordId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("RainMm")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("RelativeHumidityPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("SoilMoisture0To7Cm")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal?>("SoilMoisture100To255Cm")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal?>("SoilMoisture28To100Cm")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal?>("SoilMoisture7To28Cm")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal?>("SoilTemperatureC")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("SolarRadiationWm2")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("TemperatureC")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("WeatherCode")
                        .HasColumnType("int");

                    b.Property<string>("WeatherDescription")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WeatherLocationId")
                        .HasColumnType("int");

                    b.Property<decimal?>("WindDirectionDegrees")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("WindGustKmh")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("WindSpeedKmh")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("WeatherLocationId", "ObservedAtUtc")
                        .HasDatabaseName("IX_WeatherObservations_Location_ObservedAtUtc");

                    b.HasIndex("WeatherLocationId", "Provider", "ObservedAtUtc")
                        .IsUnique()
                        .HasDatabaseName("IX_WeatherObservations_Location_Provider_ObservedAtUtc");

                    b.ToTable("WeatherObservations", (string)null);
                });

            modelBuilder.Entity("VarnAI.WeatherSense.Domain.Entities.WeatherProviderRawResponse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CollectionExecutionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ResponseReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("WeatherLocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollectionExecutionId")
                        .HasDatabaseName("IX_WeatherProviderRawResponses_CollectionExecutionId");

                    b.HasIndex("WeatherLocationId", "RequestedAtUtc")
                        .HasDatabaseName("IX_WeatherProviderRawResponses_Location_RequestedAtUtc");

                    b.ToTable("WeatherProviderRawResponses", (string)null);
                });

            modelBuilder.Entity("VarnAI.WeatherSense.Domain.Entities.WeatherForecast", b =>
                {
                    b.HasOne("VarnAI.WeatherSense.Domain.Entities.WeatherLocation", "Location")
                        .WithMany("Forecasts")
                        .HasForeignKey("WeatherLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("VarnAI.WeatherSense.Domain.Entities.WeatherLocationExecutionDetail", b =>
                {
                    b.HasOne("VarnAI.WeatherSense.Domain.Entities.WeatherCollectionExecution", "Execution")
                        .WithMany("Details")
                        .HasForeignKey("CollectionExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VarnAI.WeatherSense.Domain.Entities.WeatherLocation", "Location")
                        .WithMany("ExecutionDetails")
                        .HasForeignKey("WeatherLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Execution");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("VarnAI.WeatherSense.Domain.Entities.WeatherObservation", b =>
                {
                    b.HasOne("VarnAI.WeatherSense.Domain.Entities.WeatherLocation", "Location")
                        .WithMany("Observations")
                        .HasForeignKey("WeatherLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("VarnAI.WeatherSense.Domain.Entities.WeatherCollectionExecution", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("VarnAI.WeatherSense.Domain.Entities.WeatherLocation", b =>
                {
                    b.Navigation("ExecutionDetails");

                    b.Navigation("Forecasts");

                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
